# Generated by Django 3.2.3 on 2021-06-25 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_picture', models.ImageField(blank=True, null=True, upload_to='cat')),
                ('actual_prize_range', models.CharField(max_length=100)),
                ('offer_prize_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('people', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='room/')),
                ('actual_prize', models.CharField(max_length=100)),
                ('offer_prize', models.CharField(max_length=100)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=10)),
                ('amount', models.FloatField()),
                ('order_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('datetime_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
