# Generated by Django 3.2.3 on 2021-06-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('QUE', 'Queen'), ('STD', 'Standard'), ('CR', 'Connecting Room'), ('KIN', 'King'), ('SUI', 'Suite'), ('PEN', 'Penthouse'), ('DEL', 'Deluxe')], default='STD', max_length=3),
        ),
    ]
