version: '3.9'

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRESS_DB=postgres
            - POSTGRESS_USER=postgres
            - POSTGRESS_PASSWORD=postgres
            # - "POSTGRES_HOST_AUTH_METHOD=trust"
    django_gunicorn :
        build: ./
        command: >-
            bash -c "python3 manage.py makemigrations && python3 manage.py migrate
            --run-syncdb && python3 manage.py collectstatic --no-input && 
            gunicorn hotel.wsgi:application --workers 3 --bind 0.0.0.0:8000"
        # container_name: 
        # command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            # - .:/app
            - static:/app/static
            - media:/app/media
        ports:
            - "8000:8000"
        depends_on: 
            - db
    nginx :
        build : ./nginx
        volumes:
            - .:/app
            - static:/app/static
            - media:/app/media
        ports: 
            - "80:80"
        depends_on: 
            - django_gunicorn
            - db

volumes:
    media :
    static :
